### ISSUE TITLE
initial version todo

### ISSUE THREAD

**Issue by ppisljar** [ppisljar/espeasy_new_ui#1]
- [x] add defaults for all devices [WIP]
- [x] add defaults for controllers
- [x] add support for notifications
- [x] add login support [WIP]
- [x] system info and system vars
- [x] improve mobile styles
- [x] improve error handling
- [x] add setup page (first connection)
- [x] espeasy p2p network status (devices connected)
- [x] documentation
